@startuml
start

:Массив и длина массива Н;
while (Шаг равен нулю?)
->No;
:Функция производит расчёт 
и возвращает результат;
if (Функция вернула значение > 400?) then (No)
:Выводим в консоль результат функции;
endif 
->Yes;
:Выводим в консоль сообщение
о превышение допустимого 
значения и индекс;

endwhile 
stop

@enduml